In [8]:
import os
import re
import pandas as pd
from collections import Counter

# Directory containing VTT files
folder_path = "/workspaces/Marquette_teaching_finance/recording_transcripts/"

# Dictionary to store speaker counts per file
all_counts = {}

# Loop through VTT files in the folder
for filename in os.listdir(folder_path):
    if filename.endswith(".vtt") and filename != "Final_presentation.vtt":
        filepath = os.path.join(folder_path, filename)
        with open(filepath, 'r', encoding='utf-8') as file:
            content = file.read()

        # Extract speaker names
        speakers = re.findall(r"<v\s+([^>]+)>", content)
        speaker_counts = Counter(speakers)

        # Use filename (without .vtt) as column name
        file_key = filename.replace(".vtt", "")
        all_counts[file_key] = speaker_counts

# Combine all counts into a DataFrame
df = pd.DataFrame(all_counts).fillna(0).astype(int)

# Add 'speakers' column from index
df["speakers"] = df.index

# Add 'total' column
df["total"] = df.drop(columns=["speakers"]).sum(axis=1)

# Reorder columns: speakers first, then totals, then the rest
cols = ["speakers", "total"] + [col for col in df.columns if col not in ["speakers", "total"]]
df = df[cols]

# Sort by total, descending
df = df.sort_values(by="total", ascending=False).reset_index(drop=True)

# Display the result
print(df)

               speakers  total  Week_0217  Week_0414  Week_0407  Week_0210  \
0             Hou, Eric  18460       1874         55         73       2216
1          Sam Iosevich    952          0          0        952          0
2                Fei Li    910          0        910          0          0
3        Haroon, Sufyan    208         28          0          0         51
4        Benbenek, MATT    118         21         15          0         19
5       Teske, Benjamin     91         11          0          1          2
6       Mertens, Aidric     90         24          5          1          0
7         Severin, Noah     70          8          0          1          8
8   Hollenbach, Patrick     68          0         21          0          0
9        Capozzoli, Jay     32          2          0          0          0
10        Matt Benbenek     26          0          0          0          0
11    Benbenek, Matthew     24          0          0          0          0
12       Guiter, Sophia     23          0          0          0          0
13      Weidner, Declan     22          2          0          0          1
14         Carone, Matt     20          1          0          0          2
15     Brozynski, Jaden     18          0          0          0          0
16     Mizwicki, Andrew     17          1          0          0          0
17        Halm, William     13          1          0          0          0
18          Barbel, Sam     13          0          0          0          0
19      Schembari, John      8          4          0          0          1
20        Myers, Nathan      7          7          0          0          0
21      Galligan, Willy      7          0          0          0          0
22         Bodine, Will      6          1          0          0          0
23     Huebner, Kaitlyn      6          0          0          0          0
24     Vargas, Cristian      5          0          0          0          0
25  Ziemianin, Jonathan      4          0          0          0          0
26         Fox, Katelyn      2          0          0          0          0

    Week_0127  Week_0324  Week_0303  Week_0317  Week_0414_2  Week_0113_2  \
0        1825       1942       2062       1886         1214         1074
1           0          0          0          0            0            0
2           0          0          0          0            0            0
3           6          3         19          5           10            5
4          18          7         17         18            3            0
5          13          4         14          3           10            8
6           9          0          2          5           13            7
7          10          1          1          3            1           14
8           7          0          0          3            8           15
9           8          0          0          0            0           14
10          0          0          0          0            0           16
11          0          0          0          0            0            0
12          0          0          0          0            0           18
13          2          0          0          0            1            5
14          6          0          1          1            1            3
15         11          0          0          0            0            0
16          2          1          0          3            0            1
17          0          0          0          0            0            1
18          3          0          0          0            0            0
19          1          0          0          0            1            0
20          0          0          0          0            0            0
21          0          0          0          0            0            0
22          0          0          0          0            0            1
23          0          0          0          0            0            1
24          0          0          0          0            0            0
25          0          0          0          0            0            0
26          0          0          0          0            0            0

    Week_0113  Week_0224  Week_0407_2
0         904       2193         1142
1           0          0            0
2           0          0            0
3          18          7           56
4           0          0            0
5          23          0            2
6          17          4            3
7          18          3            2
8          11          3            0
9           8          0            0
10         10          0            0
11          0         24            0
12          5          0            0
13         10          1            0
14          4          1            0
15          7          0            0
16          9          0            0
17         11          0            0
18         10          0            0
19          0          1            0
20          0          0            0
21          7          0            0
22          4          0            0
23          5          0            0
24          5          0            0
25          4          0            0
26          2          0            0

In [9]:
df.head()

,speakers,total,Week_0217,Week_0414,Week_0407,Week_0210,Week_0127,Week_0324,Week_0303,Week_0317,Week_0414_2,Week_0113_2,Week_0113,Week_0224,Week_0407_2
0,"Hou, Eric",18460,1874,55,73,2216,1825,1942,2062,1886,1214,1074,904,2193,1142
1,Sam Iosevich,952,0,0,952,0,0,0,0,0,0,0,0,0,0
2,Fei Li,910,0,910,0,0,0,0,0,0,0,0,0,0,0
3,"Haroon, Sufyan",208,28,0,0,51,6,3,19,5,10,5,18,7,56
4,"Benbenek, MATT",118,21,15,0,19,18,7,17,18,3,0,0,0,0

In [10]:
df.to_csv('class_frequency.csv', index = False)

In [1]:
import os
import re
import pandas as pd
from collections import Counter

# Directory containing VTT files
folder_path = "/workspaces/Marquette_teaching_finance/recording_transcripts/"

# Dictionary to store speaker counts per file
all_counts = {}

# Loop through VTT files in the folder
for filename in os.listdir(folder_path):
    if filename.endswith(".vtt") and filename == "Final_presentation.vtt":
        filepath = os.path.join(folder_path, filename)
        with open(filepath, 'r', encoding='utf-8') as file:
            content = file.read()

        # Extract speaker names
        speakers = re.findall(r"<v\s+([^>]+)>", content)
        speaker_counts = Counter(speakers)

        # Use filename (without .vtt) as column name
        file_key = filename.replace(".vtt", "")
        all_counts[file_key] = speaker_counts

# Combine all counts into a DataFrame
df = pd.DataFrame(all_counts).fillna(0).astype(int)

# Add 'speakers' column from index
df["speakers"] = df.index

# Add 'total' column
df["total"] = df.drop(columns=["speakers"]).sum(axis=1)

# Reorder columns: speakers first, then totals, then the rest
cols = ["speakers", "total"] + [col for col in df.columns if col not in ["speakers", "total"]]
df = df[cols]

# Sort by total, descending
df = df.sort_values(by="total", ascending=False).reset_index(drop=True)

# Display the result
print(df)

               speakers  total  Final_presentation
0             Hou, Eric    482                 482
1      Mizwicki, Andrew    243                 243
2   Hollenbach, Patrick    157                 157
3       Teske, Benjamin    139                 139
4       Galligan, Willy    122                 122
5       Mertens, Aidric    110                 110
6        Haroon, Sufyan    110                 110
7       Schembari, John    109                 109
8          Carone, Matt    106                 106
9         Myers, Nathan    101                 101
10       Benbenek, MATT     93                  93
11        Halm, William     85                  85
12        Severin, Noah     84                  84
13      Weidner, Declan     60                  60
14          Barbel, Sam     59                  59
15        Haque, Aleema     43                  43
16     Brozynski, Jaden     42                  42
17     Vargas, Cristian     28                  28
18     Huebner, Kaitlyn     24                  24
19         Bodine, Will     23                  23

In [2]:
df.to_csv('final_frequency.csv', index = False)